### ISSUE TITLE
Load Image from inspire pack broke .wepp save

### ISSUE THREAD

**Issue by TPYcz** [audioscavenger/save-image-extended-comfyui#24] opened 2024-09-06 09:33 UTC
If is in workflow node "Load Image" form inspire pack, saved .wepp is significantly bigger and workflow saved in picture file is uncoplete/broken.

**Comment by audioscavenger** [comment] 2024-12-20 01:38
this is significantly troublesome. JK. I cannot reproduce. 

Yes it does load your images as a base64 flat string that weights even more then the loaded image itself, inside the prompt itself. But that's not my fault, it's what Inspire Load Image does. perfectly expected.

now, I found out that my webp are not corrupt, just bigger because of the shear size of the prompt itself.
**please upgrade and retest.**
And then post an image with workflow corruption here if you can

**Comment by audioscavenger** [comment] 2024-12-20 01:48
after careful analysis, **Load Image // Inspire** is working as intended and blows out your prompt+workflow with 2x the size of the loaded image, inside the output image, making it maybe 300% bigger.

won't fix

**Closed as completed by audioscavenger** 2024-12-20 01:48 UTC
Labels: question, wontfix
